name: Github CI

on:
  push:
    branches:
      - main

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        run: 'yarn install'
  build:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Build project
        run: |
          echo "Building the project..."
          yarn build

  linters:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Run linters
        run: |
          echo "Running linters..."
          yarn linters

  deploy:
    runs-on: ubuntu-latest
    needs:
      - dependencies
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Deploy application
        run: |
          echo "Deploying the application..."
          yarn deploy
